language: elixir

sudo: false

elixir:
  - 1.4.0
otp_release:
  - 19.2

env:
  - MIX_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database manihome_test;' -U postgres
  - mix ecto.migrate

before_deploy:
  - mix docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/
  on:
    branch: master